# These categories will be applied to all DAGs in the repo.
categories:
  - Data Quality
  - ETL/ELT
# List of DAGs that should be published to the Astronomer Registry.
dags:
  - path: dags/create_table_setup_teardown_postgres.py
  - path: dags/create_table_setup_teardown_snowflake.py
  - path: dags/structure_increment_table_setup_teardown.py